name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Set Databricks Environment
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Update Repo (Auto Pull)
        run: |
          databricks repos update \
          --path "/Repos/uprishi450@gmail.com/Databricks_POC_Rishi" \
          --branch main

      - name: Trigger Job
        run: |
          databricks jobs run-now \
          --job-id 693755545747281
